import * as grpc from '@grpc/grpc-js';
import { BooksService, BooksServer } from './generated/proto/book'; // This is generated by ts-proto
import { GetAllBooksRequest, GetBooksResponse } from './generated/proto/book'; // Message types

// Implementation of the BookService
const bookServiceImpl: BooksServer = {
  getAllBooks: (call, callback) => {
    // Simulating database call or business logic
    console.log({ call })

    callback(null, {
      books: [
        { author: 'michael scofield', isbn: '123456', title: 'prisonbreak' }
      ]
    });
  }
};

// Create and start the gRPC server
const server = new grpc.Server();

server.addService(BooksService, bookServiceImpl);

const PORT = `0.0.0.0:${process.env.GRPC_PORT}`;
server.bindAsync(PORT, grpc.ServerCredentials.createInsecure(), () => {
  console.log(`gRPC server running on ${PORT}`);
  server.start();
});
